title: A Blog Title
email: bryan_schuetz@dai.com
description: | 
  A gem based theme with universal grid, styles, and layout for use with all individually styled DAI blogs
baseurl: "" 
url: "" 
github_username:  bryanschuetz

# Build settings
markdown: kramdown
destination: "./build"
permalink: "/:title"
collections:
   uploads:
    title: Uploads
    output: true