 title: The Theme
email: bryan_schuetz@dai.com
description: | 
  A gem based them with universal grid, styles, and layout for use with all individually styled DAI blogs
baseurl: "" 
url: "" 
github_username:  bryanschuetz

# Build settings
markdown: kramdown